before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: cidrgrep-darwin
    ldflags:
      - -s -w -X github.com/dotnetmentor/cidrgrep/version.Version={{.Version}} -X github.com/dotnetmentor/cidrgrep/version.Commit={{.FullCommit}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: cidrgrep-linux
    ldflags:
      - -s -w -X github.com/dotnetmentor/cidrgrep/version.Version={{.Version}} -X github.com/dotnetmentor/cidrgrep/version.Commit={{.FullCommit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: cidrgrep-archive
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: cidrgrep
    tap:
      owner: dotnetmentor
      name: homebrew-tap
    commit_author:
      name: "Kristoffer Ahl"
    homepage: https://github.com/dotnetmentor/cidrgrep
    description: like grep but for IP/CIDR matching
    license: Apache License 2.0
    install: |
      bin.install 'cidrgrep'
      output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
      (bash_completion/'cidrgrep').write output
      output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
      (zsh_completion/'_cidrgrep').write output
